# Generated by Django 4.2.6 on 2023-12-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file_field', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
