# Generated by Django 4.2.6 on 2023-12-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mymodel_delete_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Upload',
        ),
    ]
