# Generated by Django 4.2.6 on 2024-01-17 22:22

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_mymodel_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_field',
            field=models.FileField(upload_to='app/static/uploads', validators=[app.models.validate_audio_or_video_file]),
        ),
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
