# Generated by Django 4.2.6 on 2024-01-17 22:40

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_upload_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_field',
            field=models.FileField(upload_to='app/static/uploads', validators=[app.models.validate_file_size, app.models.validate_audio_or_video_file]),
        ),
    ]
